# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbb860cef803545e2736b26ed10993d81c5a2e36fbdf457e89cb14df7307ae79b003f49fb5d077e82e21d23b3bcb807c6558414a91d4c1da36f9258e10978b35

test:
  secret_key_base: 2f786975743721bc48bcccf5588328e500f9a21150d01c4d9db37ea680c3b1cff0bd73ea7750a63fcbc9c830710d58629f948a3aa180f141321660594ee0079b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
